services:
  conmasd:
    image: 386jp/conmasd:latest
    # build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/data/config.json
      - ./cert.pem:/data/cert.pem
      - ./gha-baseimg-compose.yml:/data/gha-baseimg-compose.yml
